site_name: Bible Background
site_description: Reference library of biblical context notes.
site_url: https://woodwardmw.github.io/bible-background/
repo_url: https://github.com/woodwardmw/bible-background
docs_dir: content
use_directory_urls: true
theme:
  name: material
  language: en
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/brightness-auto
      name: Following your browser. Click for light.
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Light. Click for dark.
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Dark. Click to follow your browser.
  features:
  - navigation.top
  - navigation.tracking
  - search.highlight
  - toc.follow
nav:
- Home: index.md
- Genesis:
  - Overview: genesis/index.md
  - Chapter 2: genesis/2.md
- Judges:
  - Chapter 14: judges/14.md
  - Chapter 15: judges/15.md
- Isaiah:
  - Chapter 24: isaiah/24.md
  - Chapter 25: isaiah/25.md
- 1 Peter:
  - Chapter 3: 1-peter/3.md
  - Chapter 4: 1-peter/4.md
- Reading days:
  - Sat 22 Aug 2026: days/2026-08-22.md
  - Fri 21 Aug 2026: days/2026-08-21.md
plugins:
- search
markdown_extensions:
- admonition
- toc:
    permalink: true
